// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzzbn4yAHTCjJoYhJSUeegBhIk_V06a_c',
    appId: '1:140819805916:web:56cbab5f36c2d9f1612619',
    messagingSenderId: '140819805916',
    projectId: 'teentaaj',
    authDomain: 'teentaaj.firebaseapp.com',
    storageBucket: 'teentaaj.appspot.com',
    measurementId: 'G-9RMTBE6YV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4p25iRIJF1Tg1WIF1Q98Sr00jxuNME4k',
    appId: '1:140819805916:android:002a5eb345d06c02612619',
    messagingSenderId: '140819805916',
    projectId: 'teentaaj',
    storageBucket: 'teentaaj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgM_Szv9hP4F9lQ0_6HAKmEiap7qp7Ek',
    appId: '1:140819805916:ios:0a6e1061ee47d8c6612619',
    messagingSenderId: '140819805916',
    projectId: 'teentaaj',
    storageBucket: 'teentaaj.appspot.com',
    iosBundleId: 'com.example.teentaj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfgM_Szv9hP4F9lQ0_6HAKmEiap7qp7Ek',
    appId: '1:140819805916:ios:f0f07095f0fe373a612619',
    messagingSenderId: '140819805916',
    projectId: 'teentaaj',
    storageBucket: 'teentaaj.appspot.com',
    iosBundleId: 'com.example.teentaj.RunnerTests',
  );
}
